"""empty message

Revision ID: 684d7aa25b31
Revises: 
Create Date: 2019-06-08 18:25:32.333270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684d7aa25b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sku', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
